version: '2'
services:
  xls2txt_1:
    image: whiteboxio/xls2txt:alpine-0.1.0
    command: bundle exec thin start -p 9595
    environment:
      - RACK_ENV=production
    volumes:
      - /app/public
  nginx_1:
    image: whiteboxio/nginx:alpine-0.1.0
    restart: always
    links:
      - xls2txt_1:xls2txt_1
    ports:
      - 80:80
    volumes_from:
      - xls2txt_1
    volumes:
      - /app/public
