version: '2'
services:
  xls2txt_1:
    image: whiteboxio/xls2txt:alpine-0.1.0
    command: bundle exec thin start -p 9595
    environment:
      - RACK_ENV=production
    volumes:
      - /usr/local/www/xls2txt/public
      - /etc/nginx/conf.d/xls2txt.whitebox.io
  iraand_me_1:
    image: 4pcbr/iraand.me:latest
    volumes:
      - /usr/local/www/iraand.me
      - /etc/nginx/conf.d/iraand.me
  fryreadsonegin_com_1:
    image: whiteboxio/fryreadsonegin_com:latest
    volumes:
      - /usr/local/www/fryreadsonegin.com/public
      - /usr/local/web/fryreadsonegin.com/download:/usr/local/www/fryreadsonegin.com/download
      - /etc/nginx/conf.d/fryreadsonegin.com
  whitebox_io_nginx_1:
    image: whiteboxio/whitebox_io_nginx:latest
    volumes:
      - /etc/nginx/conf.d/whitebox.io
  whitebox_io_1:
    image: whitebox
    environment:
      - MIX_ENV=production
  nginx_1:
    image: whiteboxio/nginx:alpine-0.1.0
    restart: always
    ports:
      - 80:80
    volumes_from:
      - iraand_me_1:ro
      - xls2txt_1:ro
      - whitebox_io_nginx_1:ro
      - i_whitebox_io_nginx_1:ro
      - fryreadsonegin_com_1:ro
    volumes:
      - /etc/nginx/conf.d
  i_whitebox_io_nginx_1:
    image: whiteboxio/i_whitebox_io_nginx:latest
    volumes:
      - /etc/nginx/conf.d/i.whitebox.io
      - /usr/local/web/i.whitebox.io:/usr/local/www/i.whitebox.io/public
  #i_whitebox_io_1:
    #command: bundle exec thin start -p 7171
    #image: whiteboxio/i_whitebox_io:alpine-0.1.0
    #@environment:
    #  - RACK_ENV=production
