version: '2'
services:
  xls2txt_1:
    image: whiteboxio/xls2txt:alpine-0.1.0
    command: bundle exec thin start -p 9595
    environment:
      - RACK_ENV=production
    volumes:
      - /usr/local/www/xls2txt/public
      - /etc/nginx/conf.d
  iraand_me_1:
    image: 4pcbr/iraand.me:latest
    volumes:
      - /usr/local/www/iraand.me
      - /etc/nginx/conf.d
  nginx_1:
    image: whiteboxio/nginx:alpine-0.1.0
    restart: always
    links:
      - xls2txt_1:xls2txt_1
      - iraand_me_1:iraand_me_1
    ports:
      - 80:80
    volumes_from:
      - xls2txt_1
      - iraand_me_1
    volumes:
      - /etc/nginx/conf.d
